language: cpp
dist: trusty
compiler: g++
sudo: required

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install qtchooser qt5-default
  - sudo apt-get install qt5-qmake 
  - sudo apt-get install qtdeclarative5-dev
  - sudo apt-get install libx11-dev libxrandr-dev
#  - source /opt/qt58/bin/qt58-env.sh


script:
  - cd ./src/
  - mkdir build
  - cd ./build
  - QT_SELECT=5 QTDIR=/usr/share/qt5 qmake ../
  - make
